package:
    type:           yii2-extension
    name:           hidev-scrutinizer
    title:          Scrutinizer plugin for HiDev
    headline:       HiDev Scrutinizer
    keywords:       scrutinizer, hidev, plugin, continuous integration
    namespace:      hidev\scrutinizer
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin enables [Scrutinizer](https://scrutinizer-ci.org/) support for HiDev.

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
