package:
    type:           yii2-extension
    name:           hidev-scrutinizer
    namespace:      hidev\scrutinizer
    headline:       HiDev Scrutinizer
    title:          Scrutinizer plugin for HiDev
    keywords:       scrutinizer, hidev, plugin, continuous integration
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [Scrutinizer](https://scrutinizer-ci.org/) support for HiDev.

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-hiqdev:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
